name: real-estate-scrape

on:
  workflow_dispatch:
  schedule:
    - cron:  '00 05 * * *'

jobs:
  real-estate-scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install real-estate-scrape and dependencies
      run: |
        pip install .
    - name: Run real-estate-scrape
      env:
        REDFIN_URL: ${{ secrets.REDFIN_URL }}
        ZILLOW_URL: ${{ secrets.ZILLOW_URL }}
        SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
      run: real-estate-scrape
    - name: Commit and push if it changed
      run: |-
        git config --global user.name "scraper-bot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Scraped at ${timestamp}" || exit 0
        git push
    - name: Set workflow status
      # success if NaN is not present in last line of data.csv
      run: tail -1 data.csv | grep -q -v NaN
